# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Item.create(title:'' , year: ,  director:'' ,  description:'' ,  duration: , link:'www.netflix.com' , type_item:3)

#Peliculas
Item.create(title:'Venom' , year: 2018,  director: 'Ruben Fleischer',  description:'Venom es una película de supervillanos, basada en el personaje de Marvel, Venom' ,  duration:140 , link:'www.netflix.com' , type_item:0)
Item.create(title:'Olade crimenes' , year:2018 ,  director:'Gracia Querejeta' ,  description:'El hijo adolescente de Leyre (Maribel Verdú), un ama de casa acomodadamente divorciada, mata a su padre en un arrebato. Ella decide hacer lo imposible por ocultarlo, desatando a su pesar una caótica ola de crímenes en la ciudad de Bilbao. Mientras, la nueva esposa del difunto (Paula Echevarría) y su implacable abogada (Juana Acosta) tratan de ocultar la jugosa trama de corrupción en la que se movían. Pero no habían contado con la perseverancia de la pareja de inspectores' ,  duration:98 , link:'www.netflix.com' , type_item:0)
Item.create(title:'Ha nacido una estrella' , year:2018 ,  director:'Bradley Cooper' ,  description:'A Star Is Born es una película estadounidense de romance, drama y musical dirigida por Bradley Cooper. Es la tercera adaptación cinematográfica de A Star Is Born, que fue dirigida por William A. Wellman. ' ,  duration:140 , link:'www.netflix.com' , type_item:0)
Item.create(title:'Christopher Robin, un reencuentro inolvidable' , year:2018 ,  director:'Marc Forster' ,  description:'Christopher Robin ha crecido y, ahora que es adulto, ha olvidado a sus amigos de la infancia y ha perdido el rumbo. Winnie the Pooh y sus compañeros viajan a Londres para salvar a Christopher y ayudarle a reencontrar la alegría.' ,  duration:85 , link:'www.netflix.com' , type_item:0)
Item.create(title:'Johnny English: De nuevo en acción' , year:2018 ,  director:'David Kerr' ,  description:'Johnny English Strikes Again es una película británica de acción y comedia dirigida por David Kerr. Es una secuela de la película de 2011 Johnny English Reborn y la tercera entrega de la saga Johnny English.' ,  duration:76 , link:'www.netflix.com' , type_item:0)
Item.create(title:'La monja' , year:2018 ,  director:'Corin Hardy' ,  description:'Una monja se suicida en una abadía rumana y El Vaticano envía a un sacerdote y una novicia a investigar lo sucedido. Lo que ambos encuentran allá es un secreto perverso que les enfrentará cara a cara con el mal en su esencia más pura.' ,  duration:82 , link:'www.netflix.com' , type_item:0)
Item.create(title:'El reino' , year:2018 ,  director:'Rodrigo Sorogoyen' ,  description:'El reino​ es una película española de 2018 dirigida por Rodrigo Sorogoyen y producida por Atresmedia Cine​, Tornasol Films​ y Trianera PC AIE en colaboración de Le Pacte y Mondex & CIE. Se trata de un thriller de índole política sobre la corrupción en España' ,  duration:130 , link:'www.netflix.com' , type_item:0)
Item.create(title:'Milla 22' , year:2018 ,  director:'Peter Berg' ,  description:'Mile 22 es una película de acción e intriga dirigida por Peter Berg y protagonizada por Mark Wahlberg, cuya fecha de estreno para su proyección en cines se anunció a partir del 3 de agosto de 2018 en Estados Unidos​ y posteriormente se atrasó hasta el 17 de ese mismo mes' ,  duration:160 , link:'www.netflix.com' , type_item:0)
Item.create(title:'Todos lo saben' , year:2018 ,  director:'Asghar Farhadi' ,  description:'Todos lo saben es una película de 2018 dirigida y escrita por Asghar Farhadi, es un coproducción entre España, Francia e Italia y está protagonizada por Penélope Cruz, Javier Bardem y Ricardo Darín. Su rodaje comenzó el 21 de agosto de 2017 en España​ y finalizaba en diciembre del mismo año.' ,  duration:132 , link:'www.netflix.com' , type_item:0)
Item.create(title:'Un pequeño favor' , year: 2018,  director:'Paul Feig' ,  description:'En un pequeño pueblo de los Estados Unidos, una vloguera investiga la súbita y misteriosa desaparición de su mejor amiga.' ,  duration:120 , link:'www.netflix.com' , type_item:0)
Item.create(title:'Searching' , year:2018 ,  director:'Aneesh Chaganty' ,  description:'Searching es una película estadounidense de suspenso psicológico dirigida por Aneesh Chaganty y protagonizada por John Cho y Debra Messing. La película está filmada desde el punto de vista de pantallas de celulares y computadoras, y sigue la historia de un padre intentando encontrar a su hija de 16 años perdida.' ,  duration:182 , link:'www.netflix.com' , type_item:0)

#Series
Item.create(title:'Anatomía de Grey' , year:2005 ,  director:' Betsy Beers, Krista Vernoff, Shonda Rhimes' ,  description:'Meredith Grey (Ellen Pompeo, Daredevil, El compromiso) es hija de una de las cirujanas más respetadas de la profesión. Ahora, ella quiere seguir los pasos de su madre en el Hospital Grace' ,  duration:42 , link:'www.netflix.com' , type_item:1)
Item.create(title:'The Good Doctor' , year:2017 ,  director:' David Shore' ,  description:'The Good Doctor se centra en un joven y brillante cirujano que padece el síndrome de Savant. Poco se sabe de este "síndrome del sabio" además de que aquellos que lo sufren tienen una memoria prodigios' ,  duration:42 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Vikingos' , year:2013 ,  director:'Michael Hirst' ,  description:'Este nuevo drama histórico, dirigido por Michael Hirst (Elizabeth, The Tudors), de History Channel está centrado en Ragnar Lothbrok, figura mítica que aseguraba que era el descendiente de Odín' ,  duration:52 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Juego de Tronos' , year:2011 ,  director:'David Benioff, D.B. Weiss' ,  description:'HBO, desde la calidad que caracteriza a la cadena, nos brinda una vez más una magistral adaptación televisiva de la serie de novelas Canción de hielo y fuego' ,  duration:52 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Los 100' , year:2014 ,  director:'Jason Rothenberg' ,  description:'Los 100 es un drama post apocalíptico escrito por Jason Rothenberg (Body Politic), basado en los libros de Kass Morgan. La historia está centrada en lo que ocurre con la civilización casi cien años...' ,  duration:42 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Riverdale' , year:2017 ,  director:' Roberto Aguirre-Sacasa' ,  description:'Al mismo tiempo que un nuevo año escolar da comienzo, la ciudad de Riverdale aún está reponiéndose de la trágica muerte reciente de Jason Blossom.' ,  duration:42 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Big bang' , year:2007 ,  director:'Steven Molaro, Steve Holland, Chuck Lorre' ,  description:'Trata las peripecias de un grupo de geeks, cuyos conocimientos de física superan la brillantez pero que, sin embargo, sus habilidades sociales son de lo más limitadas. ' ,  duration:22 , link:'www.netflix.com' , type_item:1)
Item.create(title:'The Walking Dead' , year:2010 ,  director:'Glen Mazzara, Scott M. Gimple, Robert Kirkman' ,  description:'La historia nos traslada a un escenario post-pandémico en el que un virus ha acabado con la práctica totalidad de la población mundial convirtiéndolos en zombis. ' ,  duration:44 , link:'www.netflix.com' , type_item:1)
Item.create(title:'American Horror Story' , year:2011 ,  director:'Ryan Murphy, Brad Falchuk, Ryan Murphy' ,  description:'Narra en cada una de sus temporadas una historia independiente ambientada en lugares y con personajes distintos. La primera de la historias que trata la serie habla sobre la vida de la familia Harmon con tintes terroríficos que recuerdan a Paranormal Activity ' ,  duration:42 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Vivir sin permiso' , year:2017 ,  director:'Aitor Gabilondo' ,  description:'La trama de Vivir sin permiso se desarrolla en Galicia y se centra en la historia de Nemesio ‘Nemo’ Bandeira, un hombre que siempre estuvo ligado a las actividades del narcotráfico gallego.' ,  duration:75 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Las Chicas del Cable' , year:2017 ,  director:'Teresa Fernández-Valdés, Ramón Campos, Gema R. Neira' ,  description:'Las Chicas del Cable, ambientada en los años 20 en la ciudad de Madrid, cuenta la historia de cuatro mujeres que proceden de distintos lugares del país. ' ,  duration:50 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Lucifer' , year:2016 ,  director:'Joe Henderson, Tom Kapinos' ,  description:'La historia de Lucifer es la que todos conocemos: un ángel caído del cielo. Sin embargo, este señor del infierno está aburrido de su propia existencia. ' ,  duration:42 , link:'www.netflix.com' , type_item:1)
Item.create(title:'Gigantes' , year:2018 ,  director:'Enrique Urbizu, Manuel Gancedo' ,  description:'La historia gira en torno a tres hermanos que están inmersos en el mundo del narcotráfico. La compraventa de drogas es la economía familiar, pero hay uno de ellos que prefiere ganarse la vida de otra forma' ,  duration:52 , link:'www.netflix.com' , type_item:1)


#Audios
Item.create(title:'Lo siento' , year:2018 ,  director:'Beret' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'In My Mind' , year:2018 ,  director:'Dynoro & Gigi D’Agostino' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Solo' , year:2018 ,  director:'Clean Bandit Feat. Demi Lovato' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Promises' , year:2018 ,  director:'Calvin Harris & Sam Smith' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Leave A Light On' , year:2018 ,  director:'Tom Walker' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Shotgun' , year:2018 ,  director:'George Ezra' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Perdon' , year:2018 ,  director:'David Bisbal & Greeicy' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Ni la hora' , year:2018 ,  director:'Ana Guerra & Juan Magan' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Él No Soy Yo' , year:2018 ,  director:'Blas Cantó' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Fuego' , year:2018 ,  director:'Eleni Foureira' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'Taki taki' , year:2018 ,  director:'DJ Snake Feat. Selena Gomez & Ozuna & Cardi B' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
Item.create(title:'One kiss' , year:2018 ,  director:'Calvin Harris & Dua Lipa' ,  description:'' ,  duration:204 , link:'www.www.spotify.com' , type_item:3)
